version: "3"

services:
  db:
    image: mysql:8.3
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pass
      TZ: Asia/Seoul
    restart: always