spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always

github:
  user: user
  token: token
